name: Lobby
version: '${project.version}'
main: net.trustgames.lobby.Lobby
api-version: 1.19
depend:
  - Core
  - LuckPerms
authors: [ Wega ]
description: Lobby for TrustGames.net
website: www.trustgames.net
#commands: - Using Cloud command framework's automatic registration
